name: Build and Deploy Docker image to Azure Container Registry

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  REGISTRY: mindrederacr.azurecr.io
  IMAGE_NAME: mindreader

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Log in to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: ${{ env.REGISTRY }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t $REGISTRY/$IMAGE_NAME:latest .
        docker push $REGISTRY/$IMAGE_NAME:latest

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v3
      with:
        app-name: MindReaderDocker
        slot-name: production
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest

